# -*- coding: utf-8 -*-
"""tutorila-nltk-nb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yeWCs75Zw4MFQaXb9HIPf1NwJ4oHs-Dh

### regex
"""

import re
texto = "o bibliotecário abriu a biblioteca"
resultado = re.findall(r'biblio\w*', texto)
print(resultado)

texto = "uma pessoa boa"
resultado = re.search(r'pessoa', texto)
print(resultado)
print(texto[4:10])
print(resultado.group(0))

"""# NLTK"""

#precisa rodar o comando: pip install nltk

import nltk
nltk.download('machado')
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('rslp')
nltk.download('mac_morpho')

"""## corpus e classe text"""

from nltk.corpus import machado
machado.fileids()

raw_text = machado.raw('romance/marm05.txt')
print(raw_text[5600:5800])

texto1 = machado.words('romance/marm05.txt')
print(texto1)
print(len(texto1))

from nltk.text import Text
bras = Text(machado.words('romance/marm05.txt'))

print(bras.concordance('olhos'))
print(bras.similar('chegar'))
print(bras.findall("<olhos> (<.*>)"))

"""## stopwords"""

stopwords = nltk.corpus.stopwords.words('portuguese')
print(stopwords[:10])

"""## colocações e bigramas"""

from nltk import bigrams
list(bigrams(['meu', 'coração', 'está', 'bem', 'machucado']))


print(bras.collocations())

"""## stemmers"""

stemmer = nltk.stem.RSLPStemmer()
print(stemmer.stem("copiar"))
print(stemmer.stem("paisagem"))

"""## tokenização"""

sentence = """Estou bem, mas não tenho certeza
... se viajarei amanhã às 8:30."""

tokens = nltk.word_tokenize(sentence)
print(tokens)

"""# problemas práticos

## POS-tagging
"""

from nltk.corpus import mac_morpho
sentencas_etiquetadas = mac_morpho.tagged_sents()
print(sentencas_etiquetadas)

tags = [tag for (word, tag) in mac_morpho.tagged_words()]
print(nltk.FreqDist(tags).max())

etiqPadrao = nltk.tag.DefaultTagger('N')
print(etiqPadrao.tag(tokens))

"""## N-Gram tagging"""

tagged_sents = nltk.corpus.mac_morpho.tagged_sents()
texto = 'A manhã está ensolarada'
tokens = nltk.word_tokenize(texto)
unigram_tagger = nltk.tag.UnigramTagger(tagged_sents)
unigram_tagger.tag(tokens)

t0 = nltk.DefaultTagger('N')
t1 = nltk.UnigramTagger(tagged_sents, backoff=t0)
t2 = nltk.BigramTagger(tagged_sents, backoff=t1)
t3 = nltk.TrigramTagger(tagged_sents, backoff=t2)

"""### Salvando um tagger

"""

from pickle import dump
output = open('mac_morpho.pkl', 'wb')
dump(t3, output, -1)
output.close()

"""### Carregando um tagger treinado

"""

from pickle import load
input = open('mac_morpho.pkl', 'rb')
tagger = load(input)
input.close()

"""## extração de informação"""

sentences = nltk.sent_tokenize(text) #segmentação em sentenças
sentences = [nltk.word_tokenize(sent) for sent in sentences] # segmentação das sentenças em tokens
sentences = [tagger.tag(sent) for sent in sentences] # etiquetagem dos tokens
print(sentences)

"""### chunking"""

text = "João comprou um carro esportivo"
tokens = nltk.word_tokenize(text)
tagged = tagger.tag(tokens)
gramatica = r"""PADRAO: {<N><ADJ>+}"""
analiseGramatical = nltk.RegexpParser(gramatica)
print(analiseGramatical.parse(tagged))

"""### reconhecimento de entidade nomeada"""

text = "O ministro Edson Fachin do Supremo Tribunal Federal determimou a separação do inquérito contra o presidente Michel Temer da investigação contra o senador afastado Aécio Neves."
tokens = nltk.word_tokenize(text)
tagged = tagger.tag(tokens)
gramatica = r"""NE: {<NPROP>+}"""
analiseGramatical = nltk.RegexpParser(gramatica)
print(analiseGramatical.parse(tagged))

"""### extração de relações"""

text = 'A estátua foi criada pelo escultor George Silva, que nasceu na Romênia'
tokens = nltk.word_tokenize(text)
tagged = tagger.tag(tokens)
gramatica = r""" NE: {<NPROP>+}
REL: {<NE> <.*>* <PREP.*> <.*>* <NE>} """
analiseGramatical = nltk.RegexpParser(gramatica)
print(analiseGramatical.parse(tagged))